version: '3'

volumes:
  postgres_data:
  postgres_backup:
  ipython_data:

services:
  postgres:
    image: cbpo-financial-postgres
    build: ./compose/postgres
    container_name: cbpo-financial-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    env_file:
      - config/settings/.env

  redis:
    image: redis:latest

  django:
    image: cbpo-django-financial-prod
    build:
      context: .
      dockerfile: compose/django/Dockerfile
    container_name: cbpo-django-financial-prod
    depends_on:
      - postgres
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - ENVIRONMENT=production
      - DEBUG=False
    env_file:
      - config/settings/.env
    ports:
      - "8000:8000"

    links:
      - postgres
      - redis

  celeryworker:
    image: cbpo-celeryworker-financial-prod
    build:
      context: .
      dockerfile: compose/django/Dockerfile
    command: /start-celery-worker.sh
    container_name: cbpo-celeryworker-financial-prod
    depends_on:
      - postgres
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - ENVIRONMENT=production
      - DEBUG=False
    env_file:
      - config/settings/.env
    links:
      - postgres
      - redis

  celerybeat:
    image: cbpo-celerybeat-financial-prod
    build:
      context: .
      dockerfile: compose/django/Dockerfile
    command: /start-celery-beat.sh
    container_name: cbpo-celerybeat-financial-prod
    depends_on:
      - postgres
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - ENVIRONMENT=production
      - DEBUG=False
    env_file:
      - config/settings/.env
    links:
      - postgres
      - redis