replicaCount: _REPLICAS_

image:
  repository: _REGISTRY_/_PROJECT_ID_/_APP_NAME_
  tag: _VERSION_
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80
  containerPort: _PORT_

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.com/health-checks: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 500m
    memory: 800Mi
  requests:
    cpu: 300m
    memory: 400Mi

livenessProbe:
  httpGet:
    path: /healthz
    port: http
    scheme: HTTP
  initialDelaySeconds: 50
  periodSeconds: 30
  timeoutSeconds: 5
readinessProbe:
  httpGet:
    path: /healthz
    port: http
    scheme: HTTP
  initialDelaySeconds: 50
  periodSeconds: 30
  timeoutSeconds: 3

nodeSelector: {}

tolerations: []

affinity: {}

configmap:
  # Base
  APP_VERSION: _VERSION_
  DJANGO_DEBUG: "False"
  DEBUG: "False"
  USE_DOCKER: "yes"

  # Environment
  ENVIRONMENT: development

  # Base url
  BASE_URL: http://localhost

  # General settings
  DJANGO_ADMIN_URL:  "^'admin/'"
  DJANGO_SETTINGS_MODULE: "config.settings.production"
  DJANGO_SECRET_KEY: _DJANGO_SECRET_KEY_
  DJANGO_ALLOWED_HOSTS: '*'

  # Oauth2
  ACCESS_TOKEN_EXPIRE_SECONDS: "2592000"

  # Celery
  CELERY_BROKER_URL: redis://10.100.0.3:6379/0

  # Used with email
  DJANGO_MAILGUN_API_KEY: default
  DJANGO_SERVER_EMAIL: default
  MAILGUN_SENDER_DOMAIN: default

  # Mail backend
  DJANGO_EMAIL_BACKEND: django.core.mail.backends.smtp.EmailBackend
  DJANGO_DEFAULT_FROM_EMAIL: "admin <no-reply@hdwebsoft.co>"

  # SMTP Mailer
  EMAIL_BACKEND: django.core.mail.backends.smtp.EmailBackend
  EMAIL_HOST: smtp.sendgrid.net
  EMAIL_HOST_PASSWORD: _SENDGRID_API_KEY_
  EMAIL_HOST_USER: apikey
  EMAIL_PORT: "587"
  EMAIL_USE_TLS: "True"

  # Security! Better to use DNS for this task, but you can use redirect
  DJANGO_SECURE_SSL_REDIRECT: "False"

  # PostgreSQL
  DATABASE_URL: postgres://_POSTGRES_USERNAME_:_POSTGRES_PASSWORD_@10.56.80.3:5432/pf-postgres-_DEPLOYMENT_TYPE_
  POSTGRES_DB: pf-postgres-_DEPLOYMENT_TYPE_
  POSTGRES_USER: _POSTGRES_USERNAME_
  POSTGRES_PASSWORD: _POSTGRES_PASSWORD_
  POSTGRES_HOST: 10.56.80.3

  # Google API
  GOOGLE_CLOUD_STORAGE_BUCKET_NAME: "precise"
  GOOGLE_CLOUD_STORAGE_BUCKET_ACCESS_KEY: "./certificates/precise-7fb53dd47513.json"

  # Bugsnag
  BUGSNAG_API_KEY: _BUGSNAG_API_KEY_

  # Asymmetric Keys Path
  PRIVATE_KEY_PATH: /config/cer/private_key.pem
  PUBLIC_KEY_PATH: /config/cer/public_key.pem
  JWT_EXPIRATION_DELTA: "2880"

  # Redis
  USER_CLIENT_REDIS_CHANNEL: redis://10.100.0.3:6379/0
  REDIS_TTL: "5"
  USER_CLIENT_REDIS_ENABLED: "True"

  # Firebase
  FIRE_BASE_ACCESS_KEY: ./cer/precise-b1d88d3b3f76.json
  FIRE_BASE_REAL_TIME_DB_URL: https://precise-9c34f.firebaseio.com/
  FIRE_BASE_REF: /
  USER_CLIENT_FIRE_BASE_ENABLED: "True"

  # Portal service URL
  URL_PORTAL_SERVICE: http://portal-api.qa.channelprecision.com

  # DS service URL
  URL_DS_SERVICE: http://ds-api.qa.channelprecision.com

  # AC service URL
  URL_AC_SERVICE: http://ac-api.qa.channelprecision.com
  AC_API_KEY: 7ev4daqef5b5xzzwmuds4es52g6xpaty66p9sj4c
  AC_SERVICE_LIMIT_ITEM: "50"

  # DC service URL
  URL_DC_SERVICE: http://dc-api.qa.channelprecision.com
  DC_SERVICE_LIMIT_ITEM: "50"

  # next cent
  PLAT_IMPORT_ROUND_UP: 0.01

  # folder save file pf
  PLAT_IMPORT_STORAGE_FOLDER: pf/lib_imports

  # FedEx Shipment range date
  DAY_RANGE_FEDEX_SHIPMENT: "10"

  # FedEx EDI config FTP
  # Note: This config for pass unittest, pls update ftp connect when build environment
  FTP_FEDEX_HOST: ftp.demo.com
  FTP_FEDEX_USER: demo
  FTP_FEDEX_PASSWD: demo
  FTP_FEDEX_PORT: 21
  FTP_FEDEX_DIR_PREFIX: precise/fedex

  # ES
  ELASTICSEARCH_URL_DEFAULT: http://localhost:9200

secret:


secretLink:
